apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: nordnet-portal-loic
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: nordnet-portal-loic
    apps.tanzu.vmware.com/has-tests: "true"
spec:
  source:
    git:
      url: https://github.com/Loyc59/nordnet-demo.git
      ref:
        branch: main
